name: Docker Multi-Build & Sign

on:
  workflow_dispatch:
  push:
    branches: [ "main", "build/docker/**" ]
    # trigger only when files in Docker/ folder change
    paths:
      - 'Docker/**'
  pull_request:
    branches: [ "main", "build/docker/**" ]
    paths:
      - 'Docker/**'

env:
  REGISTRY: ghcr.io
  # Base image name (service name will be appended as a suffix)
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Required for Cosign signing

    strategy:
      fail-fast: false
      matrix:
        # List the folder names to build here
        service: [
            '1-Decoy-spectra-generation',
            '2-1-Download-casanovo-config',
            '2-2-De-novo-peptide-sequencing 3',
            '3-Feature-calculation',
            '4-Percolator-and-FDRControl'
            ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Check for changes in the specific Docker service folder
      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'Docker/${{ matrix.service }}/**'

      # 2. Install cosign (only if there are changes and not a PR)
      - name: Install cosign
        if: steps.filter.outputs.changed == 'true' && github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # 3-1. Set up QEMU (only if there are changes or manual trigger)
      - name: Set up QEMU
        if: steps.filter.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@v3

      # 3-2. Set up Docker Buildx (only if there are changes)
      - name: Set up Docker Buildx
        if: steps.filter.outputs.changed == 'true'
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # 4. Log into registry (only if there are changes and not a PR)
      - name: Log into registry ${{ env.REGISTRY }}
        if: steps.filter.outputs.changed == 'true' && github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Extract Docker metadata (append service name to image name)
      - name: Extract Docker metadata
        if: steps.filter.outputs.changed == 'true'
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          # ì˜ˆ: ghcr.io/owner/repo-1-asdf
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service }}

      # 6. Build and push Docker image (Context path updated to subfolder)
      - name: Build and push Docker image
        if: steps.filter.outputs.changed == 'true'
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          # Set context to the subfolder containing the Dockerfile
          context: Docker/${{ matrix.service }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 7. Sign image (only if there are changes and not a PR)
      - name: Sign the published Docker image
        if: steps.filter.outputs.changed == 'true' && github.event_name != 'pull_request'
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}